name: app_chi_tieu
description: "Mini app chi tieu ca nhan"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1           # Quản lý trạng thái
  http: ^1.4.0               # Gọi API (kết nối tới backend dùng MongoDB)
  image_picker: ^1.0.7       # Chụp ảnh hóa đơn
  path_provider: ^2.1.2      # Lấy đường dẫn lưu ảnh tạm
  path: ^1.9.0               # Xử lý đường dẫn ảnh
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  flutter_svg: ^2.0.7
  table_calendar: ^3.0.9
  date_picker_timeline: ^1.2.5
  shared_preferences: ^2.5.3
  fl_chart: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true
